services:
  app:
    build: .
    image: sandboxed-node-app:latest
    container_name: sandboxed-node-app
    ports:
      - '8293:8293'
    volumes:
      - .:/usr/src/app # Mount the current directory to the container
      - /usr/src/app/node_modules # Prevent the node_modules from being mounted
    restart: always
# docker-compose up --build
