[package]
name = "rust_code_runner"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.211", features = ["derive"] }
serde_derive = "1.0.211"
serde_json = "1.0.132"
tokio = { version = "1.41.0", features = ["full"] }
warp = "0.3.7"
wasmtime = "25.0.2"
