services:
  app:
    build: .
    image: public-ip:latest # 이미지 이름 지정
    container_name: public-ip # 컨테이너 이름 지정
    volumes:
      - .:/usr/src/app
    ports:
      - '5028:5028' # 포트 매핑
    command: node server.mjs
    restart: always # 자동 재시작 설정


# docker-compose up --build
# docker-compose down
